name: Bug report
description: Create a report to help us improve

labels: ["bug"]
assignees: ["scarf005"]

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reaching out!

        Please make sure that you're

        - using concise title (e.g:`Amplified Shoot The Moon uses 3 energy instead of 2`).
        - using the latest version of this mod.
        - using minimal set of mods enabled to reproduce the bug.

        ## Console

        To make reproducing bugs easier, please use basemod's **[Console](https://alexdriedger.github.io/SlayTheSpireModding/docs/console)** command, surrounded with backtick (`` ` ``) for each steps.

        ### How to enable and use console

        ![mods](https://user-images.githubusercontent.com/54838975/233089827-1382b9f7-74ea-4261-b020-0605964cc784.png)

        1. Visit `Mods` in the main menu.

        ![basemod](https://user-images.githubusercontent.com/54838975/233089870-e4f712dd-318c-4abc-9518-380cd448b206.png)

        2. Click `BaseMod`.
        3. Click `Enable dev console` and `Enable Autocompletion`.

        ![console usage example](https://github-production-user-asset-6210df.s3.amazonaws.com/54838975/258566362-aee9fd69-4ace-4482-b345-2fc8b87ab1c2.png)

        4. Open console using (`` ` ``) key (the key right below ESC key which also has `~`).
        5. Use console command to reproduce the bug.

  - type: input
    attributes:
      label: Mod version
      description: Please make sure the bug is reproducible in latest version of the mod.
      placeholder: x.x.x
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce
      description: Console steps that reliably reproduce the bug. Screenshot or Videos are also welcome.
      placeholder: |
        1. Start a new game with Marisa.
        2. `fight Lagavulin`
        3. `hand add ShootTheMoon 1 0`
        4. Use the generated ShootTheMoon card to attack Lagavulin.

        Despite card description (1 base cost + 1 amplify cost), it uses 3 energy.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Game language
      description: Which language were you using in the game?
      multiple: false
      options:
        - English (ENG)
        - French (FRA)
        - Japanese (JPN)
        - Korean (KOR)
        - Simplified Chinese (ZHS)
        - Traditional Chinese (ZHT)
        - Spanish (SPA)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Crash log
      description: If the game crashed, please paste the crash log here.
      placeholder: |
        Version Info:
        - Java version (1.8.0_144)
        - Slay the Spire (12-18-2022)
        - ModTheSpire (3.30.0)
        Mod list:
        - basemod (5.47.0)
        - MarisaContinued (1.5.1)
        Cause:
        java.lang.StringIndexOutOfBoundsException: String index out of range: 1
          at java.lang.String.charAt(String.java:658)
          at com.megacrit.cardcrawl.helpers.FontHelper.identifyColor(FontHelper.java:1218)
          at com.megacrit.cardcrawl.helpers.FontHelper.renderSmartText(FontHelper.java:953)
          at com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreen.renderModInfo(ModsScreen.java:354)
          at com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreen.render(ModsScreen.java:221)
          at com.evacipated.cardcrawl.modthespire.patches.modsscreen.ModsScreenUpdateRender$Render.Postfix(ModsScreenUpdateRender.java:32)
          at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.render(MainMenuScreen.java:622)
          at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:435)
          at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
          at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
