name: Bug report
description: Create a report to help us improve

labels: ["bug"]
assignees: ["scarf005"]

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reaching out!

        please make sure that you're
        - using consise title (e.g:`Amplified Shoot The Moon uses 3 energy instead of 2`).
        - using the latest version of this mod.

  - type: textarea
    attributes:
      label: How to reproduce
      description: >
        To make reproducing bugs easier, please use basemod's
        **[Console](https://alexdriedger.github.io/SlayTheSpireModding/docs/console)**
        command, surrounded with backtick (\`) for each steps.
        Screenshot or Videos are also welcome.
      placeholder: |
        1. Start a new game with Marisa.
        2. `fight Lagavulin`
        3. `hand add ShootTheMoon 1 0`
        4. Use the generated ShootTheMoon card to attack Lagavulin.

        Despite card description (1 base cost + 1 amplify cost), it uses 3 energy.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Crash log
      description: If the game crashed, please paste the crash log here.
