name: Localization
description: Help us improve or fix wrong translations

labels: ["localization"]

body:
  - type: dropdown
    attributes:
      label: Language
      description: Which language will be affected?
      multiple: true
      options:
        - English
        - French
        - Japanese
        - Korean
        - Simplified Chinese
        - Traditional Chinese
        - Others
    validations:
      required: true

  - type: textarea
    attributes:
      label: Summary
      description: Please describe the issue in detail.
      placeholder: Orrerys Sun gives block but power text is attack
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you interested in fixing this issue?
      options:
        - label: I am willing to PR a fix for this issue.
